[package]
name = "wasmedge_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
wasmedge_sys_ffi = { path = "../wasmedge_sys_ffi" }

[features]
default = ["plugin"]
wasi = []
embedded = ["wasi"]
plugin = []
